{ pkgs, lib, config, ... }:

let
  karabiner = import ./karabiner.nix { inherit lib; };

  # The complex_modifications asset, in the format karabiner_cli can lint.
  assetFile = pkgs.writeText "naginata-v18.json" (builtins.toJSON {
    title = "Naginata-shiki v18";
    rules = [ karabiner.rule ];
  });

  # Just the one rule object, for the surgical jq patch below.
  ruleFile = pkgs.writeText "naginata-v18-rule.json"
    (builtins.toJSON karabiner.rule);

  # Used only when Karabiner has never been configured on this machine.
  seedFile = pkgs.writeText "karabiner-seed.json" (builtins.toJSON {
    global.show_in_menu_bar = true;
    profiles = [{
      name = "Default profile";
      selected = true;
      complex_modifications.rules = [ ];
    }];
  });

  macSKKApp = "${pkgs.macskk}/Library/Input Methods/macSKK.app";
  stockKanaRule = "${macSKKApp}/Contents/Resources/kana-rule.conf";

  # Prepended to the generated table so `head` on the live file says which
  # layout it belongs to. macSKK ignores `#` lines.
  kanaRuleHeader = pkgs.writeText "kana-rule-naginata-header.conf" ''
    # GENERATED by dotfiles naginata/default.nix -- do not edit.
    #
    # Naginata-shiki v18: macSKK ${pkgs.macskk.version}'s stock table plus the
    # ？ / ！ rows from naginata/kana-rule-extra.conf. Every one of the layout's
    # 159 romaji sequences is verified against exactly this file.
    #
    # This is Settings/kana-rule.conf, the table macSKK 2.8.x loads
    # unconditionally and the one 2.10.0+ lists as "kana-rule.conf". The AZIK
    # table lives next to it as kana-rule-azik.conf and is NOT compatible with
    # this layout: 31 sequences break under it (naginata/README.md).
  '';

  karabinerDir = "${config.home.homeDirectory}/.config/karabiner";
  macSKKSettingsDir =
    "${config.home.homeDirectory}/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Settings";

  manipulatorCount = toString karabiner.stats.total;
in
{
  home.activation.naginataSetup = lib.mkIf pkgs.stdenv.isDarwin (
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      KARABINER_JSON="${karabinerDir}/karabiner.json"
      ASSET_DIR="${karabinerDir}/assets/complex_modifications"
      SETTINGS_DIR="${macSKKSettingsDir}"

      $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$ASSET_DIR"
      $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$SETTINGS_DIR"

      # Drop the asset in as well, so the rule can be inspected or re-enabled
      # from Karabiner's own UI.
      $DRY_RUN_CMD ${pkgs.coreutils}/bin/install -m 644 \
        ${assetFile} "$ASSET_DIR/naginata-v18.json"

      if [ ! -f "$KARABINER_JSON" ]; then
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/install -m 644 \
          ${seedFile} "$KARABINER_JSON"
      fi

      # Replace only our own rule, matched on its description, leaving every
      # other rule and setting in karabiner.json alone. Enabling a rule in the
      # UI copies it into karabiner.json, so editing the asset by itself would
      # never reach a rule that has already been enabled.
      #
      # The redirects below are guarded on DRY_RUN rather than prefixed with the
      # deprecated $DRY_RUN_CMD: `echo cmd > file` still truncates the file and
      # writes the echoed command line into it.
      if [[ -v DRY_RUN ]]; then
        echo "would patch $KARABINER_JSON with rule ${karabiner.description}"
        echo "would write $SETTINGS_DIR/kana-rule.conf"
      else
        ${pkgs.jq}/bin/jq \
          --slurpfile rule ${ruleFile} \
          '.profiles |= map(
             .complex_modifications.rules =
               (((.complex_modifications.rules // [])
                 | map(select(.description != $rule[0].description)))
                + [$rule[0]])
           )' \
          "$KARABINER_JSON" > "$KARABINER_JSON.naginata-tmp" \
          && ${pkgs.coreutils}/bin/mv \
               "$KARABINER_JSON.naginata-tmp" "$KARABINER_JSON"

        # Naginata's kana rule: stock table + the ？ / ！ rows, written to the
        # path macSKK actually loads. Before this owned kana-rule.conf, the
        # macSKK module's AZIK table sat here and the layer's romaji ran through
        # AZIK instead -- r+p (しゅ) came out すうう, g+h (ちゃ) ちゅうあ and
        # q+j (ぁ) しゃ, because AZIK reads sh as すう, ch as ちゅう and xa as しゃ.
        ${pkgs.coreutils}/bin/cat \
          ${kanaRuleHeader} "${stockKanaRule}" ${./kana-rule-extra.conf} \
          > "$SETTINGS_DIR/kana-rule.conf"

        # The same table used to be written under this name, where macSKK 2.8.x
        # could not reach it at all. Remove it only if it is still byte-identical
        # to what generated it, so a hand-edited copy survives.
        if [ -f "$SETTINGS_DIR/kana-rule-naginata.conf" ]; then
          if ${pkgs.coreutils}/bin/cat "${stockKanaRule}" ${./kana-rule-extra.conf} \
               | ${pkgs.diffutils}/bin/cmp -s - "$SETTINGS_DIR/kana-rule-naginata.conf"; then
            ${pkgs.coreutils}/bin/rm "$SETTINGS_DIR/kana-rule-naginata.conf"
          else
            echo "note: $SETTINGS_DIR/kana-rule-naginata.conf differs from the"
            echo "      generated table and was left in place. It now shows up as"
            echo "      a second entry in macSKK's kana rule dropdown."
          fi
        fi
      fi

      $DRY_RUN_CMD echo ""
      $DRY_RUN_CMD echo "================================================"
      $DRY_RUN_CMD echo "Naginata-shiki v18"
      $DRY_RUN_CMD echo "================================================"
      $DRY_RUN_CMD echo "OK  Karabiner rule installed (${manipulatorCount} manipulators)"
      $DRY_RUN_CMD echo "OK  kana-rule.conf written (stock + ？ / ！)"
      $DRY_RUN_CMD echo ""
      $DRY_RUN_CMD echo "Manual steps:"
      $DRY_RUN_CMD echo "1. Launch Karabiner-Elements once and grant Input"
      $DRY_RUN_CMD echo "   Monitoring plus the driver extension."
      $DRY_RUN_CMD echo "2. System Settings > Keyboard > Input Sources:"
      $DRY_RUN_CMD echo "   add macSKK if it is not enabled yet."
      $DRY_RUN_CMD echo "3. Check which romaji table macSKK is really using:"
      $DRY_RUN_CMD echo "   see the report below. Every kana symptom this layout"
      $DRY_RUN_CMD echo "   can have starts there (naginata/README.md)."
      $DRY_RUN_CMD echo ""

      # Which table is live is the single most useful thing to know when a kana
      # comes out wrong, and it cannot be derived from the Nix side: 2.8.x always
      # loads Settings/kana-rule.conf, while 2.10.0+ loads whatever `kanaRule`
      # names ("" meaning the app's built-in table, which lacks the ？ / ！ rows).
      MACSKK_INSTALLED="/Library/Input Methods/macSKK.app"
      MACSKK_PLIST="$HOME/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Library/Preferences/net.mtgto.inputmethod.macSKK.plist"
      INSTALLED_VERSION="$(/usr/bin/defaults read "$MACSKK_INSTALLED/Contents/Info.plist" CFBundleShortVersionString 2>/dev/null || true)"
      SELECTED_RULE="$(/usr/bin/defaults read "$MACSKK_PLIST" kanaRule 2>/dev/null || true)"

      $DRY_RUN_CMD echo "macSKK installed: ''${INSTALLED_VERSION:-none} (nixpkgs has ${pkgs.macskk.version})"
      if [ "$INSTALLED_VERSION" != "${pkgs.macskk.version}" ]; then
        $DRY_RUN_CMD echo "  -> refresh it:  sudo cp -R '${macSKKApp}' /Library/Input\ Methods/"
        $DRY_RUN_CMD echo "     2.10.0+ is what lets you switch tables at all."
      fi
      if [ -z "$SELECTED_RULE" ]; then
        $DRY_RUN_CMD echo "kana rule selected: (none set)"
        $DRY_RUN_CMD echo "  2.8.x  -> Settings/kana-rule.conf is used. Correct."
        $DRY_RUN_CMD echo "  2.10.0+ -> the built-in table is used: all 159 kana"
        $DRY_RUN_CMD echo "     work, but ？ / ！ stay half-width. Select"
        $DRY_RUN_CMD echo "     kana-rule.conf in Settings > ローマ字かな変換ルール."
      elif [ "$SELECTED_RULE" = "kana-rule.conf" ]; then
        $DRY_RUN_CMD echo "kana rule selected: kana-rule.conf  <- correct"
      else
        $DRY_RUN_CMD echo "kana rule selected: $SELECTED_RULE  <- WRONG for this layout"
        $DRY_RUN_CMD echo "  Select kana-rule.conf in Settings > ローマ字かな変換ルール."
      fi
      $DRY_RUN_CMD echo ""
      $DRY_RUN_CMD echo "Nix owns the rule named:"
      $DRY_RUN_CMD echo "  ${karabiner.description}"
      $DRY_RUN_CMD echo "Disabling it in the Karabiner UI is undone by the next"
      $DRY_RUN_CMD echo "home-manager switch."
      $DRY_RUN_CMD echo "================================================"
      $DRY_RUN_CMD echo ""
    ''
  );
}
