# Naginata-shiki v18 layout table (kana only).
#
# GENERATED by tools/assign-romaji.py. See README.md to regenerate.
#
# Source: 大岡俊彦, "薙刀式配列v18（トップ版）" (Yamabuki-R definition)
#   https://oookaworks.up.seesaa.net/image/E89699E58880E5BC8Fv18.txt
#
# The kana-to-key mapping below is a transcription of that published layout
# and is NOT covered by this repository's UNLICENSE -- it remains the
# original author's work. See README.md's "License" section.
#
# This table is IME independent: it maps a kana to the set of physical keys
# that produce it. `romaji` is the keystroke sequence handed to the IME.
#
# REQUIRES macSKK's STOCK kana-rule.conf (verified against 2.8.0 and
# 2.14.0). Every sequence commits one kana at a time and leaves no pending
# romaji there, so the stock table needs no edits.
#
# It is NOT compatible with this repo's AZIK rule (macSKK/azik-overrides.conf).
# That rule redefines xa/xi/xu/xe/xo as the sha-row and turns kw/gw/tw/dw/th/dh
# into two-vowel expansions, which breaks 31 of the sequences below. Select a
# stock/plain-romaji rule while using this layout. See README.md.
#
# Key names use Karabiner-Elements key_code spelling. Note that ー is the one
# entry whose romaji is not a letter: emit it as the `hyphen` key_code.
# The center shift is the space bar: hold it to reach the shift plane.
#
# Out of scope on purpose: symbols, letters, the number row, the v18 edit
# modes and the proper-noun shortcuts.
{
  meta = {
    version = "v18";
    source = "https://oookaworks.up.seesaa.net/image/E89699E58880E5BC8Fv18.txt";
    author = "Toshihiko Ooka (大岡俊彦)";
  };

  # Held to reach the shift plane.
  centerShift = "spacebar";

  # Chord role keys. Not used by the generator; kept as a reading aid.
  roleKeys = {
    leftDakuten = "f";  # 左濁: voices right-hand kana
    rightDakuten = "j";  # 右濁: voices left-hand kana
    leftHandakuten = "v";  # 左半: semi-voices right-hand kana
    rightHandakuten = "m";  # 右半: semi-voices left-hand kana
    small = "q";  # 小: makes the kana small
  };

  # Unshifted plane (26)
  #
  #   q=-    w=き   e=て   r=し   t=-    y=-    u=-    i=る   o=す   p=へ
  #   a=ろ   s=け   d=と   f=か   g=っ   h=く   j=あ   k=い   l=う   ;=ー
  #   z=ほ   x=ひ   c=は   v=こ   b=そ   n=た   m=な   ,=ん   .=ら   /=れ
  #
  #   q has no unshifted kana (it is the small-kana chord key).
  #   t y u are edit keys -> optional.editing
  #
  single = [
    { key = "w"; kana = "き"; romaji = "ki"; }
    { key = "e"; kana = "て"; romaji = "te"; }
    { key = "r"; kana = "し"; romaji = "si"; }
    { key = "i"; kana = "る"; romaji = "ru"; }
    { key = "o"; kana = "す"; romaji = "su"; }
    { key = "p"; kana = "へ"; romaji = "he"; }
    { key = "a"; kana = "ろ"; romaji = "ro"; }
    { key = "s"; kana = "け"; romaji = "ke"; }
    { key = "d"; kana = "と"; romaji = "to"; }
    { key = "f"; kana = "か"; romaji = "ka"; }
    { key = "g"; kana = "っ"; romaji = "xtu"; }
    { key = "h"; kana = "く"; romaji = "ku"; }
    { key = "j"; kana = "あ"; romaji = "a"; }
    { key = "k"; kana = "い"; romaji = "i"; }
    { key = "l"; kana = "う"; romaji = "u"; }
    { key = "semicolon"; kana = "ー"; romaji = "-"; }
    { key = "z"; kana = "ほ"; romaji = "ho"; }
    { key = "x"; kana = "ひ"; romaji = "hi"; }
    { key = "c"; kana = "は"; romaji = "ha"; }
    { key = "v"; kana = "こ"; romaji = "ko"; }
    { key = "b"; kana = "そ"; romaji = "so"; }
    { key = "n"; kana = "た"; romaji = "ta"; }
    { key = "m"; kana = "な"; romaji = "na"; }
    { key = "comma"; kana = "ん"; romaji = "nn"; }
    { key = "period"; kana = "ら"; romaji = "ra"; }
    { key = "slash"; kana = "れ"; romaji = "re"; }
  ];

  # Shift plane: hold spacebar (25)
  #
  #   q=-    w=ね   e=り   r=め   t=-    y=-    u=さ   i=よ   o=え   p=ゆ
  #   a=せ   s=み   d=に   f=ま   g=ち   h=や   j=の   k=も   l=つ   ;=ふ
  #   z=ほ   x=ひ   c=を   v=-    b=ぬ   n=お   m=-    ,=む   .=わ   /=れ
  #
  #   t y are Shift+Left / Shift+Right -> optional.editing
  #   v m are 、/。 followed by Enter   -> optional.punctuation
  #
  shift = [
    { key = "w"; kana = "ね"; romaji = "ne"; }
    { key = "e"; kana = "り"; romaji = "ri"; }
    { key = "r"; kana = "め"; romaji = "me"; }
    { key = "u"; kana = "さ"; romaji = "sa"; }
    { key = "i"; kana = "よ"; romaji = "yo"; }
    { key = "o"; kana = "え"; romaji = "e"; }
    { key = "p"; kana = "ゆ"; romaji = "yu"; }
    { key = "a"; kana = "せ"; romaji = "se"; }
    { key = "s"; kana = "み"; romaji = "mi"; }
    { key = "d"; kana = "に"; romaji = "ni"; }
    { key = "f"; kana = "ま"; romaji = "ma"; }
    { key = "g"; kana = "ち"; romaji = "ti"; }
    { key = "h"; kana = "や"; romaji = "ya"; }
    { key = "j"; kana = "の"; romaji = "no"; }
    { key = "k"; kana = "も"; romaji = "mo"; }
    { key = "l"; kana = "つ"; romaji = "tu"; }
    { key = "semicolon"; kana = "ふ"; romaji = "fu"; }
    { key = "z"; kana = "ほ"; romaji = "ho"; }
    { key = "x"; kana = "ひ"; romaji = "hi"; }
    { key = "c"; kana = "を"; romaji = "wo"; }
    { key = "b"; kana = "ぬ"; romaji = "nu"; }
    { key = "n"; kana = "お"; romaji = "o"; }
    { key = "comma"; kana = "む"; romaji = "mu"; }
    { key = "period"; kana = "わ"; romaji = "wa"; }
    { key = "slash"; kana = "れ"; romaji = "re"; }
  ];

  # Chords (108). Press order does not matter: Karabiner's
  # from.simultaneous is order insensitive, so v18's mirrored definitions
  # collapse into one entry each.
  #
  # Evaluate three-key chords before two-key ones: every two-key chord
  # below is a subset of at least one three-key chord.
  combos = [
    # -- dakuten (voiced) (21)
    { keys = [ "e" "j" ]; kana = "で"; romaji = "de"; }
    { keys = [ "a" "j" ]; kana = "ぜ"; romaji = "ze"; }
    { keys = [ "d" "j" ]; kana = "ど"; romaji = "do"; }
    { keys = [ "u" "f" ]; kana = "ざ"; romaji = "za"; }
    { keys = [ "o" "f" ]; kana = "ず"; romaji = "zu"; }
    { keys = [ "p" "f" ]; kana = "べ"; romaji = "be"; }
    { keys = [ "f" "h" ]; kana = "ぐ"; romaji = "gu"; }
    { keys = [ "f" "j" ]; kana = "が"; romaji = "ga"; }
    { keys = [ "f" "l" ]; kana = "づ"; romaji = "du"; }
    { keys = [ "f" "n" ]; kana = "だ"; romaji = "da"; }
    { keys = [ "g" "j" ]; kana = "ぢ"; romaji = "di"; }
    { keys = [ "w" "j" ]; kana = "ぎ"; romaji = "gi"; }
    { keys = [ "r" "j" ]; kana = "じ"; romaji = "ji"; }
    { keys = [ "s" "j" ]; kana = "げ"; romaji = "ge"; }
    { keys = [ "j" "z" ]; kana = "ぼ"; romaji = "bo"; }
    { keys = [ "j" "x" ]; kana = "び"; romaji = "bi"; }
    { keys = [ "j" "v" ]; kana = "ご"; romaji = "go"; }
    { keys = [ "f" "semicolon" ]; kana = "ぶ"; romaji = "bu"; }
    { keys = [ "j" "c" ]; kana = "ば"; romaji = "ba"; }
    { keys = [ "j" "b" ]; kana = "ぞ"; romaji = "zo"; }
    { keys = [ "f" "l" "semicolon" ]; kana = "ゔ"; romaji = "vu"; }
    # -- handakuten (semi-voiced) (5)
    { keys = [ "p" "v" ]; kana = "ぺ"; romaji = "pe"; }
    { keys = [ "semicolon" "v" ]; kana = "ぷ"; romaji = "pu"; }
    { keys = [ "c" "m" ]; kana = "ぱ"; romaji = "pa"; }
    { keys = [ "z" "m" ]; kana = "ぽ"; romaji = "po"; }
    { keys = [ "x" "m" ]; kana = "ぴ"; romaji = "pi"; }
    # -- small kana (11)
    { keys = [ "q" "s" ]; kana = "ヶ"; romaji = "xke"; }
    { keys = [ "q" "i" ]; kana = "ょ"; romaji = "xyo"; }
    { keys = [ "q" "o" ]; kana = "ぇ"; romaji = "xe"; }
    { keys = [ "q" "p" ]; kana = "ゅ"; romaji = "xyu"; }
    { keys = [ "q" "f" ]; kana = "ヵ"; romaji = "xka"; }
    { keys = [ "q" "h" ]; kana = "ゃ"; romaji = "xya"; }
    { keys = [ "q" "j" ]; kana = "ぁ"; romaji = "xa"; }
    { keys = [ "q" "k" ]; kana = "ぃ"; romaji = "xi"; }
    { keys = [ "q" "l" ]; kana = "ぅ"; romaji = "xu"; }
    { keys = [ "q" "n" ]; kana = "ぉ"; romaji = "xo"; }
    { keys = [ "q" "period" ]; kana = "ゎ"; romaji = "xwa"; }
    # -- youon (palatalised) (23)
    { keys = [ "e" "i" ]; kana = "りょ"; romaji = "ryo"; }
    { keys = [ "e" "p" ]; kana = "りゅ"; romaji = "ryu"; }
    { keys = [ "e" "h" ]; kana = "りゃ"; romaji = "rya"; }
    { keys = [ "w" "i" ]; kana = "きょ"; romaji = "kyo"; }
    { keys = [ "r" "i" ]; kana = "しょ"; romaji = "sho"; }
    { keys = [ "i" "s" ]; kana = "みょ"; romaji = "myo"; }
    { keys = [ "i" "x" ]; kana = "ひょ"; romaji = "hyo"; }
    { keys = [ "w" "p" ]; kana = "きゅ"; romaji = "kyu"; }
    { keys = [ "r" "p" ]; kana = "しゅ"; romaji = "shu"; }
    { keys = [ "p" "s" ]; kana = "みゅ"; romaji = "myu"; }
    { keys = [ "p" "x" ]; kana = "ひゅ"; romaji = "hyu"; }
    { keys = [ "i" "d" ]; kana = "にょ"; romaji = "nyo"; }
    { keys = [ "p" "d" ]; kana = "にゅ"; romaji = "nyu"; }
    { keys = [ "d" "h" ]; kana = "にゃ"; romaji = "nya"; }
    { keys = [ "i" "g" ]; kana = "ちょ"; romaji = "cho"; }
    { keys = [ "p" "g" ]; kana = "ちゅ"; romaji = "chu"; }
    { keys = [ "g" "h" ]; kana = "ちゃ"; romaji = "cha"; }
    { keys = [ "w" "h" ]; kana = "きゃ"; romaji = "kya"; }
    { keys = [ "r" "h" ]; kana = "しゃ"; romaji = "sha"; }
    { keys = [ "s" "h" ]; kana = "みゃ"; romaji = "mya"; }
    { keys = [ "h" "x" ]; kana = "ひゃ"; romaji = "hya"; }
    { keys = [ "e" "p" "m" ]; kana = "てゅ"; romaji = "thu"; }
    { keys = [ "p" "semicolon" "v" ]; kana = "ふゅ"; romaji = "fwu"; }
    # -- voiced youon (14)
    { keys = [ "e" "p" "j" ]; kana = "でゅ"; romaji = "dhu"; }
    { keys = [ "w" "i" "j" ]; kana = "ぎょ"; romaji = "gyo"; }
    { keys = [ "r" "i" "j" ]; kana = "じょ"; romaji = "jo"; }
    { keys = [ "i" "j" "x" ]; kana = "びょ"; romaji = "byo"; }
    { keys = [ "p" "f" "l" ]; kana = "ゔゅ"; romaji = "vyu"; }
    { keys = [ "i" "g" "j" ]; kana = "ぢょ"; romaji = "dyo"; }
    { keys = [ "g" "h" "j" ]; kana = "ぢゃ"; romaji = "dya"; }
    { keys = [ "p" "g" "j" ]; kana = "ぢゅ"; romaji = "dyu"; }
    { keys = [ "w" "h" "j" ]; kana = "ぎゃ"; romaji = "gya"; }
    { keys = [ "r" "h" "j" ]; kana = "じゃ"; romaji = "ja"; }
    { keys = [ "h" "j" "x" ]; kana = "びゃ"; romaji = "bya"; }
    { keys = [ "w" "p" "j" ]; kana = "ぎゅ"; romaji = "gyu"; }
    { keys = [ "r" "p" "j" ]; kana = "じゅ"; romaji = "ju"; }
    { keys = [ "p" "j" "x" ]; kana = "びゅ"; romaji = "byu"; }
    # -- semi-voiced youon (3)
    { keys = [ "i" "x" "m" ]; kana = "ぴょ"; romaji = "pyo"; }
    { keys = [ "h" "x" "m" ]; kana = "ぴゃ"; romaji = "pya"; }
    { keys = [ "p" "x" "m" ]; kana = "ぴゅ"; romaji = "pyu"; }
    # -- extended / foreign sounds (31)
    { keys = [ "e" "j" "k" ]; kana = "でぃ"; romaji = "dhi"; }
    { keys = [ "e" "k" "m" ]; kana = "てぃ"; romaji = "thi"; }
    { keys = [ "d" "j" "l" ]; kana = "どぅ"; romaji = "dwu"; }
    { keys = [ "d" "l" "m" ]; kana = "とぅ"; romaji = "twu"; }
    { keys = [ "o" "f" "h" ]; kana = "ぐぇ"; romaji = "guxe"; }
    { keys = [ "f" "h" "j" ]; kana = "ぐぁ"; romaji = "gwa"; }
    { keys = [ "f" "h" "k" ]; kana = "ぐぃ"; romaji = "guxi"; }
    { keys = [ "f" "h" "n" ]; kana = "ぐぉ"; romaji = "guxo"; }
    { keys = [ "f" "j" "l" ]; kana = "ゔぁ"; romaji = "va"; }
    { keys = [ "f" "k" "l" ]; kana = "ゔぃ"; romaji = "vi"; }
    { keys = [ "o" "f" "l" ]; kana = "ゔぇ"; romaji = "ve"; }
    { keys = [ "f" "l" "n" ]; kana = "ゔぉ"; romaji = "vo"; }
    { keys = [ "o" "g" "j" ]; kana = "ぢぇ"; romaji = "dye"; }
    { keys = [ "o" "g" "m" ]; kana = "ちぇ"; romaji = "che"; }
    { keys = [ "o" "h" "v" ]; kana = "くぇ"; romaji = "kwe"; }
    { keys = [ "h" "j" "v" ]; kana = "くぁ"; romaji = "kwa"; }
    { keys = [ "h" "k" "v" ]; kana = "くぃ"; romaji = "kwi"; }
    { keys = [ "h" "v" "n" ]; kana = "くぉ"; romaji = "kwo"; }
    { keys = [ "r" "o" "j" ]; kana = "じぇ"; romaji = "je"; }
    { keys = [ "j" "l" "v" ]; kana = "つぁ"; romaji = "tsa"; }
    { keys = [ "o" "k" "v" ]; kana = "いぇ"; romaji = "ye"; }
    { keys = [ "k" "l" "v" ]; kana = "うぃ"; romaji = "wi"; }
    { keys = [ "o" "l" "v" ]; kana = "うぇ"; romaji = "we"; }
    { keys = [ "l" "v" "n" ]; kana = "うぉ"; romaji = "who"; }
    { keys = [ "o" "semicolon" "v" ]; kana = "ふぇ"; romaji = "fe"; }
    { keys = [ "j" "semicolon" "v" ]; kana = "ふぁ"; romaji = "fa"; }
    { keys = [ "k" "semicolon" "v" ]; kana = "ふぃ"; romaji = "fi"; }
    { keys = [ "semicolon" "v" "n" ]; kana = "ふぉ"; romaji = "fo"; }
    { keys = [ "r" "o" "m" ]; kana = "しぇ"; romaji = "she"; }
    { keys = [ "f" "h" "period" ]; kana = "ぐゎ"; romaji = "guxwa"; }
    { keys = [ "h" "v" "period" ]; kana = "くゎ"; romaji = "kuxwa"; }
  ];

  # Present in v18 but outside the kana scope. Wire these up if wanted.
  optional = {
    editing = [
      { plane = "single"; keys = [ "t" ]; action = "left"; }
      { plane = "single"; keys = [ "y" ]; action = "right"; }
      { plane = "single"; keys = [ "u" ]; action = "backspace"; }
      { plane = "shift"; keys = [ "t" ]; action = "shift_left"; }
      { plane = "shift"; keys = [ "y" ]; action = "shift_right"; }
    ];
    punctuation = [
      { plane = "shift"; keys = [ "v" ]; action = "touten_enter"; }
      { plane = "shift"; keys = [ "m" ]; action = "kuten_enter"; }
    ];
  };
}
