shell = "zsh"

[plugins.base16]
github = "chriskempson/base16-shell"

[plugins.zsh-z]
github = "agkozak/zsh-z"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

