zstyle :compinstall filename '/home/shirono/.zshrc'

autoload -Uz compinit
compinit

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt autocd
unsetopt beep

alias "$"=""

# Rust package Cache Lock Resolution
# If you encounter "Blocking waiting for file lock on package cache" issue:
# Try removing the package cache file to resolve the problem
# Command: rm -rf ~/.cargo/.package-cache
if [ -d ~/.cargo/.package-cache ]; then
  rm -rf ~/.cargo/.package-cache
fi

export ZENO_GIT_CAT="bat --color=always"
export ZENO_GIT_TREE="eza --tree"

eval "$(sheldon source)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"

if [[ -n $ZENO_LOADED ]]; then
  bindkey ' '  zeno-auto-snippet
  bindkey '^m' zeno-auto-snippet-and-accept-line
  bindkey '^i' zeno-completion
  bindkey '^x ' zeno-insert-space
  bindkey '^x^m' accept-line
  bindkey '^x^z' zeno-toggle-auto-snippet
  bindkey '^r' zeno-history-selection
  bindkey '^g' zeno-ghq-cd
fi

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.nix-profile/lib/pkgconfig

